version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
      args:
        DOMAIN: ${DOMAIN}
        EMAIL: ${EMAIL}
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - application

  application:
    build:
      context: ./
      args:
        APP_ENV: $APP_ENV
    container_name: rust-auth
    ports:
      - 5000:5000
    volumes:
      # - ./migrations:/opt/app/migrations
      - ./src:/opt/app/rust-auth/src
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres-db
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      # PGUSER: ${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db:
    driver: local